### ISSUE TITLE
IchiV1

### ISSUE THREAD

**Issue by bruzska** [StudyRemy/freqtrade_stuff#1]
Hey, I discovered the IchiV1 strat through google and it seems amazing in backtests but performs poorly on a dry run. I’ve looked over the code a bunch but I can’t figure out what’s causing it to show such incredible results when backtesting. Most of the buys are triggered by a simple EMA check.  Are you able to provide any insights because I’m very confused right now!

**Comment by StudyRemy** [comment]
Hi! I don't really remember, but I think it overwrites candle data and therefore get wrong values. I'm not sure, though. Did you heck the freqtrade discord, there might be some info there.

**Comment by bruzska** [comment]
Yeah I see it now, Switching the OHLC to Heikinashi OHLC screws with the data and gives amazing results. Very disappointing. Thanks for the quick response though!

**Comment by StudyRemy** [comment]
No problem! Good luck with the strats!
